# Generated by Django 5.1.6 on 2025-03-04 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='articles/gallery/', verbose_name='Фото')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Галлерея статьи',
                'verbose_name_plural': 'Галлерея статьи',
            },
        ),
    ]
