# Generated by Django 5.1.6 on 2025-03-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Слаг'),
        ),
    ]
